version: 2.1

jobs:
  build-dev:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm install -g postcss
      - run: postcss src/crazy.css -d css --config postcss.config.js
      - persist_to_workspace:
          root: .
          paths:
            - "dist/crazy.css"

  build-prod:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm install -g postcss
      - run: postcss css/crazy.css -u cssnano -o css/crazy.min.css --no-map
      - persist_to_workspace:
          root: .
          paths:
            - "dist/crazy.min.css"

workflows:
  version: 2
  build:
    jobs:
      - build-dev
      - build-prod:
          requires:
            - build-dev
