version: 2.1

jobs:
  build-dev:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npx postcss src/crazy.css -d css --config postcss.config.js
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-prod:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: .
      - run: npm install
      - run: npx postcss css/crazy.css -u cssnano -o css/crazy.min.css --no-map
      - store_artifacts:
          path: css/crazy.min.css   
      - run:
          name: Publish to npm
          command: |
            echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
            npm publish --access public
          environment:
            NPM_TOKEN: ${{ env.NPM_USERNAME }}:${{ env.NPM_PASSWORD }}


workflows:
  version: 2
  build:
    jobs:
      - build-dev
      - build-prod:
          requires:
            - build-dev
          filters:
            branches:
              only: main
