version: 2.1

jobs:
  build-dev:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build:dev
      - persist_to_workspace:
          root: ./css
          paths:
            - "crazy.css"

  build-prod:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build:prod
      - persist_to_workspace:
          root: ./css
          paths:
            - "crazy.min.css"

workflows:
  version: 2
  build:
    jobs:
      - build-dev
      - build-prod:
          requires:
            - build-dev