name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Build development CSS
        run: postcss src/crazy.css -d dist --config postcss.config.js
      - name: Upload development CSS
        uses: actions/upload-artifact@v2
        with:
          name: crazy.css
          path: dist/crazy.css

  build-prod:
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Build production CSS
        run: postcss dist/crazy.css -u cssnano -o dist/crazy.min.css --no-map
      - name: Upload production CSS
        uses: actions/upload-artifact@v2
        with:
          name: crazy.min.css
          path: dist/crazy.min.css

